trigger:
  - none

parameters:
  - name: targetEnv
    displayName: Target Environment
    type: string
    default: azure
    values:
      - azure
      - aws

variables:
  - template: azdo-templates/variables.yaml

stages:
  - template: azdo-templates/tf-plan.yaml
  # - template: azdo-templates/tf-apply.yaml
  #   parameters:
  #     targetEnv: ${{ parameters.targetEnv }}
